language: java
jdk:
- oraclejdk7

script: mvn package

before_deploy:
    - mkdir deploy
    - cp iupload-war/target/iupload*.war deploy/

deploy:
    provider: s3
    access_key_id: AKIAJVZNZT5TTB2Y4BNA
    secret_access_key:
      secure: FLV4Zf11wjfEIMgVjiIvx8Q0IUZqxLspcwAZRu9tROby79vs8mKC/eEfgq+VIGKaLTL+U6bA6i9Dp6NJ4r+8JLCNRez4AEYHbTPDnJ+m6FcvVuBSamDHN1bEey1PTkhXsJ3hTBrBA4msZ7VFkfiiqYuyGbMcwGazEq3UcH
evo0M=
    bucket: indeedeng-imhotep-build
    local-dir: deploy
    skip_cleanup: true
